### PR TITLE
feat: PRs should be double approved to get merge

### PR DESCRIPTION
**Pull request by ariesdevil**
**Summary**
A pull request should get two reviewers' approval to get merged.

**Related issues**
#14

### CODE REVIEW

**Comment by ariesdevil** [comment]
@BohuTANG @ZhiHanZ @drmingdrmer PTAL

**Comment by drmingdrmer** [comment]
It seems `/ lgtm` will not work in this mode?
Such a comment just let the bot approve a PR.
Thus multiple `lgtm`s sitll count as one.

**Comment by ariesdevil** [comment]
@drmingdrmer Every merge action cycle will fetch all reviews' state and count that.
https://github.com/datafuselabs/fusebots/pull/15/files#diff-2520491486c650bd51977f4048b0f1a55520af084eed59417017a0bd2f84e789R120-R126

**Comment by drmingdrmer** [comment]
I need to convert this pr to draft to have a test...

**Comment by drmingdrmer** [comment]
> I need to convert this pr to draft to have a test...

Nothing happened...

**Comment by drmingdrmer** [comment]
> @drmingdrmer Every merge action cycle trigged by cron will fetch all reviews' state and count that. https://github.com/datafuselabs/fusebots/pull/15/files#diff-2520491486c650bd51977f4048b0f1a55520af084eed59417017a0bd2f84e789R120-R126

What I mean is:
- I commented with `lgtm`.
- The bot approved once.
- BohuTANG commented with `lgtm`.
- The bot approved for the 2nd time.

I this case, there is only one guy approved this issue, the bot.

But they are actually from two reviewers.

**Comment by drmingdrmer** [comment]
Like this:

image

image

**Comment by ariesdevil** [comment]
> > @drmingdrmer Every merge action cycle trigged by cron will fetch all reviews' state and count that. [#15 (files)](https://github.com/datafuselabs/fusebots/pull/15/files#diff-2520491486c650bd51977f4048b0f1a55520af084eed59417017a0bd2f84e789R120-R126)
> 
> What I mean is:
> 
> * I commented with `lgtm`.
> * The bot approved once.
> * BohuTANG commented with `lgtm`.
> * The bot approved for the 2nd time.
> 
> I this case, there is only one guy approved this issue, the bot.
> 
> But they are actually from two reviewers.

Got it, I'll check the logic again.

**Comment by drmingdrmer** [comment]
A work around is to let the bot count number of `lgtm` comments.

Or we need to discard the `lgtm` way to approve: instead, switch to the traditional way: PR author requests somebody to review and reviewers click the "approve" button.

**Comment by ariesdevil** [comment]
> A work around is to let the bot count number of `lgtm` comments.
> 
> Or we need to discard the `lgtm` way to approve: instead, switch to the traditional way: PR author requests somebody to review and reviewers click the "approve" button.

Sounds good but a little bit complicated, Let me think about it again.

**Comment by ariesdevil** [comment]
@drmingdrmer @BohuTANG  I changed some logic, there are three cases:
1. two reviewers both use `/lgtm` way, then the bot approves twice, approval count is 1. In this case, we will also check if the label reaches `lgtm2` (aka. can be merged), and if it reached, the PR can be merged.
2. one reviewer use `/lgtm` way and the other one use the traditional way(click approve button), then approval count is 2, PR can be merged.
3. two reviewers both use the traditional way, same as case 2.

**Comment by BohuTANG** [comment]
I guess this will help us than we do it in fusebot:
https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-assignment-for-your-team

**Comment by drmingdrmer** [comment]
Hm...if it works, shall we just merge it and see how well it helps us?

**Comment by BohuTANG** [comment]
Update bot to the production, let see what will happend :thinking:

**Comment by BohuTANG** [comment]
It works ,but the comments is fuzz
https://github.com/datafuselabs/databend/pull/2674

**Comment by ariesdevil** [comment]
> It works ,but the comments is fuzz [datafuselabs/databend#2674](https://github.com/datafuselabs/databend/pull/2674)

Oops, I'll fix it.

**Comment by BohuTANG** [comment]
> > It works ,but the comments is fuzz [datafuselabs/databend#2674](https://github.com/datafuselabs/databend/pull/2674)
> 
> Oops, I'll fix it.

I have fixed and it works well

**Comment by ariesdevil** [comment]
> > > It works ,but the comments is fuzz [datafuselabs/databend#2674](https://github.com/datafuselabs/databend/pull/2674)
> > 
> > 
> > Oops, I'll fix it.
> 
> I have fixed and it works well

https://github.com/datafuselabs/fusebots/blob/main/actions/issue_action.go#L64  `/lgtm` should trigger label change, but nothing happened now.  https://github.com/datafuselabs/databend/pull/2676

**Comment by BohuTANG** [comment]
This PR force merged by sundy with the approve vote 1, so the label is not auto removed, I think it's by design

**Comment by BohuTANG** [comment]
Check the log file, there is nothing found related it.
We should add more logs to track it, but the merge button under control is a good choice, bot not always work well.

**Pull request merged**
